import { Minus, Plus, ShieldCheck, ShoppingBag, Trash2 } from 'lucide-react'
import toast from 'react-hot-toast'
import { useCart, useDispatchCart } from '../components/ContextReducer'
import { API_URL } from '../lib/api'

export default function Cart() {
  const items = useCart(); const dispatch = useDispatchCart(); const subtotal = items.reduce((sum, item) => sum + item.price, 0); const delivery = subtotal >= 499 || subtotal === 0 ? 0 : 49
  const saveOrder = async () => { const response = await fetch(`${API_URL}/orderData`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ order_data: items, email: localStorage.getItem('userEmail'), order_date: new Date().toLocaleString('en-IN') }) }); if (!response.ok) throw new Error('Could not save your order') }
  const cashCheckout = async () => { if (!localStorage.getItem('authToken')) return toast.error('Please sign in before checkout'); try { await saveOrder(); dispatch({ type: 'DROP' }); toast.success('Order placed — pay on delivery') } catch (error) { toast.error(error.message) } }
  const onlineCheckout = async () => { if (!localStorage.getItem('authToken')) return toast.error('Please sign in before checkout'); try { const { loadStripe } = await import('@stripe/stripe-js/pure'); const stripe = await loadStripe(import.meta.env.VITE_STRIPE_PUBLIC_KEY); if (!stripe) throw new Error('Payment is not configured'); const response = await fetch(`${API_URL}/payment`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ products: items }) }); const session = await response.json(); if (!response.ok) throw new Error('Unable to start payment'); await saveOrder(); await stripe.redirectToCheckout({ sessionId: session.id }) } catch (error) { toast.error(error.message) } }
  return <div className="cart-panel"><div className="cart-header"><span className="eyebrow">Your selection</span><h2>Shopping cart <small>{items.length}</small></h2></div>{items.length === 0 ? <div className="cart-empty"><span><ShoppingBag /></span><h3>Your cart is feeling light.</h3><p>Add a few everyday essentials and they’ll appear here.</p></div> : <><div className="cart-items">{items.map((item, index) => <article key={`${item.id}-${item.size}-${index}`}><div className="cart-item-image">{item.image ? <img src={item.image} alt="" /> : <ShoppingBag />}</div><div><h3>{item.name}</h3><p>{item.size}</p><div className="cart-quantity"><button aria-label={`Decrease ${item.name} quantity`} onClick={() => dispatch({ type: 'SET_QTY', index, qty: Math.max(1, item.qty - 1) })}><Minus /></button><span>{item.qty}</span><button aria-label={`Increase ${item.name} quantity`} onClick={() => dispatch({ type: 'SET_QTY', index, qty: item.qty + 1 })}><Plus /></button></div></div><div className="cart-item-price"><strong>₹{item.price.toFixed(2)}</strong><button aria-label={`Remove ${item.name}`} onClick={() => dispatch({ type: 'REMOVE', index })}><Trash2 /></button></div></article>)}</div><div className="cart-summary"><p><span>Subtotal</span><strong>₹{subtotal.toFixed(2)}</strong></p><p><span>Delivery</span><strong>{delivery ? `₹${delivery}` : 'Free'}</strong></p><hr /><p className="cart-total"><span>Total</span><strong>₹{(subtotal + delivery).toFixed(2)}</strong></p><small><ShieldCheck /> Taxes included. Payments are securely processed.</small></div><div className="cart-checkout"><button className="primary-button" onClick={onlineCheckout}>Pay securely online</button><button className="secondary-button" onClick={cashCheckout}>Cash on delivery</button></div></>}</div>
}
