import { useRef, useState } from 'react'
import { GoogleLogin, GoogleOAuthProvider } from '@react-oauth/google'
import { ArrowRight, Check, Eye, EyeOff } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import ReCAPTCHA from 'react-google-recaptcha'
import toast, { Toaster } from 'react-hot-toast'
import Layout from '../components/Layout'
import { API_URL, googleLogin, persistSession } from '../lib/api'

function SignupContent() {
  const [form, setForm] = useState({ name: '', email: '', password: '', geolocation: '' }); const [captcha, setCaptcha] = useState(''); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const captchaRef = useRef(); const navigate = useNavigate(); const googleEnabled = Boolean(import.meta.env.VITE_GOOGLE_CLIENT_ID)
  const completeGoogle = async ({ credential }) => { try { const data = await googleLogin(credential); persistSession(data); navigate('/') } catch (error) { toast.error(error.message) } }
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { const response = await fetch(`${API_URL}/createUser`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.name, email: form.email, password: form.password, location: form.geolocation, recaptcha: captcha }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Please check your details'); toast.success('Account created'); navigate('/login') } catch (error) { toast.error(error.message) } finally { setBusy(false) } }
  return <Layout className="auth-page"><Toaster position="bottom-center" /><section className="auth-layout"><div className="auth-story signup-story"><span className="eyebrow">Join MediKart</span><h1>Build a better<br />everyday routine.</h1><p>One thoughtful account for wellness essentials, repeat orders, and dependable care support.</p><ul><li><Check /> Browse the complete catalog</li><li><Check /> Save time on every checkout</li><li><Check /> Keep order history together</li></ul><div className="auth-quote">Simple tools for the health routines that matter.</div></div><div className="auth-card signup-card"><div><span className="eyebrow">Create an account</span><h2>Let’s get started</h2><p>Already a member? <Link to="/login">Sign in</Link></p></div>{googleEnabled ? <GoogleLogin onSuccess={completeGoogle} onError={() => toast.error('Google sign-up was cancelled')} width="360" shape="pill" text="signup_with" /> : <div className="google-config-note">Add VITE_GOOGLE_CLIENT_ID to enable Google sign-up.</div>}<div className="auth-divider"><span>or use your email</span></div><form onSubmit={submit}><div className="form-row"><label>Full name<input required minLength="2" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Delivery city<input required value={form.geolocation} onChange={(e) => setForm({ ...form, geolocation: e.target.value })} placeholder="Delhi" /></label></div><label>Email address<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<div className="password-field"><input type={show ? 'text' : 'password'} minLength="8" required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 8 characters" /><button type="button" onClick={() => setShow(!show)} aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff /> : <Eye />}</button></div></label>{import.meta.env.VITE_SITE_KEY && <ReCAPTCHA sitekey={import.meta.env.VITE_SITE_KEY} ref={captchaRef} onChange={setCaptcha} />}<button className="auth-submit" disabled={busy || (import.meta.env.VITE_SITE_KEY && !captcha)}>{busy ? 'Creating account…' : <>Create my account <ArrowRight /></>}</button></form><small className="legal-copy">By continuing, you agree to MediKart’s terms and privacy policy.</small></div></section></Layout>
}

export default function Signup() {
  const clientId = import.meta.env.VITE_GOOGLE_CLIENT_ID
  return clientId ? <GoogleOAuthProvider clientId={clientId}><SignupContent /></GoogleOAuthProvider> : <SignupContent />
}
